config/routes.rb
Rails.application.routes.draw do


  get 'ratings/show'

  #call the resources method, and pass it a Symbol.
  #This instructs Rails to create post routes for creating, updating, viewing, and deleting instances of Post.
  resources :topics do
    resources :posts, except: [:index]
    resources :sponsored_posts, except: [:index]
  end

  resources :posts, only: [] do
    resources :comments, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]

    post '/up-vote' => 'votes#up_vote', as: :up_vote
    post '/down-vote' => 'votes#down_vote', as: :down_vote
  end

  resources :users, only: [:new, :create, :show]

  resources :sessions, only: [:new, :create, :destroy]

  resources :advertisements
  resources :questions

  resources :labels, only: [:show]



  #remove get "welcome/index" because we've declared the index view as the root view.
  #We also modify the about route to allow users to type /about, rather than /welcome/about.
  post 'users/confirm' => 'users#confirm'

  get 'about' => 'welcome#about'

  get 'faq' => 'welcome#faq'

  root to: 'welcome#index'

  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :show, :create, :update]
      resources :topics, except: [:edit, :new] do
        resources :posts, except: [:edit, :new] 
      end

      resources :posts, only: [] do
        resources :favorite, only: [:create, :destroy]
        resources :comments, only: [:index, :show]
      end
    end
  end
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all
  end

  def show
    @question = Question.find(params[:id])
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new
    @question.title = params[:question][:title]
    @question.body = params[:question][:body]
    @question.resolved = params[:question][:resolved]

    if @question.save
      flash[:notice] = 'Question saved successfully'
      redirect_to @question
    else
      flash[:error] = 'Question could not be saved, please try again'
      render :new
    end
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])
    @question.title = params[:question][:title]
    @question.body = params[:question][:body]
    @question.resolved = params[:question][:resolved]

    if @question.save
      flash[:notice] = 'Question successfully updated'
      redirect_to @question
    else
      flash[:error] = 'Question could not be updated, please try again'
      render :edit
    end
  end

  def destroy
    @question = Question.find(params[:id])

    if @question.destroy
      flash[:notice] = 'Question successfully updated'
      redirect_to questions_path
    else
      flash[:error] = 'Question could not be deleted, please try again'
      render :show
    end
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/edit.html.erb
<h1>Edit Question</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for  questions</p>
    <ul>
      <li>Be sure to be clear when asking your question.</li>
      <li>No matter how frustrated you are, no profaninty is allowed.</li>
      <li>Above all, have fun!</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= form_for @question do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: "Enter question title" %>
      </div>
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter question body" %>
      </div>
      <div class="form-group">
        <%= f.label 'Resolved' %>
        <%=f.check_box :resolved %>
      </div>
      <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/questions/index.html.erb
<h1>
  All Questions
  <%= link_to 'New Question', new_question_path, class: 'btn btn-success' %>
</h1>

<% @questions.each do |question| %>
    <div class="media">
      <div class="media-body">
        <h4 class="media-heading">
          <%= link_to question.title, question %>
        </h4>
      </div>
    </div>
<% end %> 

app/views/questions/new.html.erb
<<h1>New question</h1>


<div class="row">

  <div class="col-md-4">
    <p>Guidelines for posts</p>
    <ul>
      <li>Be sure to be clear when asking your question.</li>
      <li>No matter how frustrated you are, no profaninty is allowed.</li>
      <li>Above all, have fun!</li>
    </ul>
  </div>

  <div class="col-md-8">
    <%= form_for @question do |f| %>
        <div class="form-group">
          <%= f.label :title %>
          <%= f.text_field :title, class: 'form-control', placeholder: 'enter question title' %>
        </div>

        <div class="form-group">
          <%= f.label :body %>
          <%= f.text_field :body, class: 'form-control', placeholder: 'enter question body' %>
        </div>

        <div class="form-group">
          <%= f.submit 'Save', class: 'btn btn-success' %>
        </div>
    <% end %>
  </div>

</div>

app/views/questions/show.html.erb
<h1><%= @question.title %></h1>

<div class="row">
  <div class="col-md-8">
    <p><%= @question.body %></p>
    <p>
      <% if @question.resolved %>
          This question has been resolved
      <% else %>
          This question has NOT been resolved
      <% end %>
    </p>
  </div>
  <div class="col-md-4">
    <%= link_to 'Edit Question', edit_question_path(@question), class: 'btn btn-success' %>
    <%= link_to 'Delete Question', @question, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this question?' } %>
  </div>
</div>