config/routes.rb
Rails.application.routes.draw do


  get 'ratings/show'

  #call the resources method, and pass it a Symbol.
  #This instructs Rails to create post routes for creating, updating, viewing, and deleting instances of Post.
  resources :topics do
    resources :posts, except: [:index]
    resources :sponsored_posts, except: [:index]
  end

  resources :posts, only: [] do
    resources :comments, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]

    post '/up-vote' => 'votes#up_vote', as: :up_vote
    post '/down-vote' => 'votes#down_vote', as: :down_vote
  end

  resources :users, only: [:new, :create, :show]

  resources :sessions, only: [:new, :create, :destroy]

  resources :advertisements
  resources :questions

  resources :labels, only: [:show]



  #remove get "welcome/index" because we've declared the index view as the root view.
  #We also modify the about route to allow users to type /about, rather than /welcome/about.
  post 'users/confirm' => 'users#confirm'

  get 'about' => 'welcome#about'

  get 'faq' => 'welcome#faq'

  root to: 'welcome#index'

  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :show, :create, :update]
      resources :topics, except: [:edit, :new] do
        resources :posts, except: [:edit, :new] 
      end

      resources :posts, only: [] do
        resources :favorite, only: [:create, :destroy]
        resources :comments, only: [:index, :show]
      end
    end
  end
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  has_many :posts, dependent: :destroy
  has_many :sponsored_posts

  has_many :labelings, as: :labelable
  has_many :labels, through: :labelings

  scope :visible_to, -> (user) { user ? all : publicly_viewable }
  scope :privately_viewable, -> (user) { user ? where(public: false) : nil }
  scope :publicly_viewable, -> { where(public: true) }

  has_one :rating, as: :rateable

  validates :name, length: { minimum: 5 }, presence: true
  validates :description, length: { minimum: 15}, presence: true
end

app/controllers/api/v1/topics_controller.rb
class Api::V1::TopicsController < Api::V1::BaseController

  before_filter :authenticate_user, except: [:index, :show]
  before_filter :authorize_user, except: [:index, :show]

  def index
    topics = Topic.all
    render json: topics.to_json, status: 200
  end

  def show
    topic = Topic.all
    render json: topic.to_json(include: [:posts]), status: 200
  end

  def update
    topic = Topic.find(params[:id])

    if topic.update_attributes(topic_params)
      render json: topic.to_json, status: 200
    else
      render json: { error: "Topic update failed", status: 400}, status: 400
    end
  end

  def create
    topic = Topic.new(topic_params)

    if topic.valid?
      topic.save!
      render json: topic.to_json, status: 201
    else
      render json: {error: "Topic is invalid", status: 400}, status: 400
    end
  end

  def destroy
    topic = Topic.find(params[:id])

    if topic.destroy
      render json: {message: "Topic destroyed", status: 200}, status: 200
    else
      render json: {error: "Topic destroy failed", status: 400}, status: 400
    end
  end

  private

  def topic_params
    params.require(:topic).permit(:name, :description, :public)
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

  before_action :require_sign_in, except: [:index, :show]
  before_action :authorize_user, except: [:index, :show]
  def index
    @topics = Topic.visible_to(current_user)
  end

  def show
    @topic = Topic.find(params[:id])
    @posts = @topic.posts

    unless @topic.public || current_user
      flash[:error] = "You must be signed in to view private topics."
      redirect_to new_session_path
    end
  end

  def new
    @topic = Topic.new
  end

  def create
    @topic = Topic.new(topic_params)
    if current_user.moderator?

    flash[:error] = "You are not authorized for that action."
    redirect_to @topic

    else
    if @topic.save
      @topic.labels = Label.update_labels(params[:topic][:labels])
      @topic.rating = Rating.update_rating(params[:topic][:rating])
      redirect_to @topic, notice: "Topic was successfully saved."

    else
      flash[:error] = "Error creating topic. Please try again."
      render :new
      end
    end
  end

  def edit
    @topic = Topic.find(params[:id])
  end

  def update
    @topic = Topic.find(params[:id])

    @topic.assign_attributes(topic_params)

    if @topic.save
      @topic.labels = Label.update_labels(params[:topic][:labels])
      @topic.rating = Rating.update_rating(params[:topic][:rating])
      flash[:notice] = "Topic was updated."
      redirect_to @topic
    else
      flash[:error] = "Error saving topic. Please try again."
      render :edit
    end
  end

  def destroy
    @topic = Topic.find(params[:id])
    if current_user.moderator?

    flash[:error] = "You are not authorized for that action."
    redirect_to @topic

    else
      if @topic.destroy
        flash[:notice] = "\"#{@topic.name}\" was deleted successfully."
        redirect_to action: :index
      else
        flash[:error] = 'Threre was an error in deleting the topic.'
        render :show
      end
    end
  end

  private

  def topic_params
    params.require(:topic).permit(:name, :description, :public)
  end

  def authorize_user
    unless current_user.admin? || current_user.moderator?
      flash[:error] = "You are not authorized for that action."
      redirect_to topics_path
    end
  end
end

app/helpers/topics_helper.rb
module TopicsHelper

  def user_can_create_topics?
    (current_user && current_user.admin?)
  end

  def user_can_delete_topics?
    (current_user && current_user.moderator?)
  end

  def user_can_edit_topics?
    (current_user && current_user.admin?)
  end

  def render_posts(posts)
    output = ""
    posts.each do |post|
      output += '<div class="media"><div class="media-body"><h4 class="media-heading">'
      output += link_to post.title, topic_post_path(post.topic, post)
      output += "</h4><small>submitted #{time_ago_in_words(post.created_at)} ago by #{post.user.name}<br>"
      output += "#{post.comments.count } comments" if post.respond_to?('comments')
      output += "</small></div></div>"
    end
    output.html_safe
  end

  def render_topic_name(topic, link = false)
    output = link ? link_to(topic.name, topic) : topic.name
    output += "private" unless topic.public?
    output.html_safe
  end
end

app/views/topics/_form.html.erb
<%= form_for topic do |f| %>
<% if topic.errors.any? %>
  <div class="alert alert-danger">
    <h4>There are <%= pluralize(topic.errors.count, "error") %>.</h4>
    <ul>
      <% topic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>
  <%= form_group_tag(topic.errors[:name]) do %>
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control', placeholder: "Enter topic name" %>
  <% end %>
  <%= form_group_tag(topic.errors[:description]) do %>
    <%= f.label :description %>
    <%= f.text_area :description, rows: 8, class: 'form-control', placeholder: "Enter topic description" %>
  <% end %>
  <div class="form-group">
    <%= f.label :public, class: 'checkbox' do %>
      <%= f.check_box :public %> Public topic
    <% end %>
    <div class="form-group">
      <%= render partial: 'labels/form', locals: { f: f, labels: @topic.labels } %>
    </div>
    <div class="form-group">
         <%= render partial: 'ratings/form', locals: { f: f, rating: @topic.rating } %>
    </div>
  </div>
  <%= f.submit "Save", class: 'btn btn-success' %>
<% end %>

app/views/topics/_topic.html.erb
<div class="media">
   <div class="media-body">
     <h3><%= render_topic_name(topic, true) %></h3>
     <small>
       <%= topic.description %>
     </small>
  </div>
</div>

app/views/topics/edit.html.erb
<h1>Edit Topic</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for topics:</p>
    <ul>
      <li>Make sure the topic is appropriate.</li>
      <li>Never insult animals.</li>
      <li>Smile while you type.</li>
    </ul>
  </div>
  <div class="col-me-8">
    <%= render partial: 'form', locals: { topic: @topic } %>
  </div>
  
</div>

app/views/topics/index.html.erb
<h1>Topics</h1>

<div class="row">
  <div class="col-md-8">
    <%= render @topics %>
  </div>
  <% if user_can_create_topics? %>
  <div class="col=md-4">
    <%= link_to "New Topic", new_topic_path, class: 'btn btn-success' %>
  </div>
  <% end %>
</div>
<br>
<br>

app/views/topics/new.html.erb
<h1>New Topic</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for topics:</p>
    <ul>
      <li>Make sure the topic is appropriate.</li>
      <li>Never insult dogs.</li>
      <li>Smile while you type.</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= render partial: 'form', locals: { topic: @topic } %>
  </div>
</div>

app/views/topics/show.html.erb
<h1><%= render_topic_name(@topic) %></h1>
    <p class="lead">
       <%= render partial: "labels/list", locals: { labels: @topic.labels } %>
       <%= render partial: "ratings/list", locals: { rating: @topic.rating } %>
       <br />
       <%= @topic.description %>
    </p>

<div class="col-md-4">
  <% if user_can_delete_topics? %>
    <%= link_to "Delete Topic", @topic, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this topic?'} %>
  <% end %>
  <% if user_can_edit_topics? %>
    <%= link_to "Edit Topic", edit_topic_path, class: 'btn btn-success' %>
  <% end %>
  <br>
  <% @topic.posts.each do |post| %>
      <div class="media">
        <div id="<%= 'post-#{post.id}' %>" class="voting">
        <%= render partial: 'votes/voter', locals: { post: post } %>
        </div>
        <div class="media-body">
          <h4 class="media-heading">
              <%= link_to post.title, topic_post_path(@topic, post) %>
              <%= render partial: "labels/list", locals: { labels: post.labels } %>
          </h4>
          <small>
            submitted <%= time_ago_in_words(post.created_at) %> ago by <%= post.user.name %><br>
            <%= post.comments.count %> Comments
          </small>
        </div>
      </div>
  <% end %>
</div>
<br>

<% if current_user %>
  <div class="col-md-4">
    <%= link_to "New Post", new_topic_post_path(@topic), class: 'btn btn-success' %>
    <%= link_to "New Sponsored Post", new_topic_sponsored_post_path(@topic, @sponsored_post), class: 'btn btn-success' %>
  </div>
<% end %>
<br>
<br>